{
 "title": "IPMI BMC Monitoring",
 "tags": [
  "Monitoring",
  "BMC",
  "IPMI"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "HOST",
    "label": "Node",
    "query": {
     "query": "{__name__=\"ipmi_bmc_info\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{exported_instance=\"$HOST\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{exported_instance=\"$HOST\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_power_watts{exported_instance=\"$HOST\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Voltage ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_voltage_volts{exported_instance=\"$HOST\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}